### ISSUE TITLE
Add Theme-Synchronization Task to Deploy

### ISSUE THREAD

**Issue by screeny05** [bestit/ShopwareMageTasks#3]
Theme-sync is a huge issue when developing. Developers add new Config-Parameters to the Theme.php of the Theme in order to give the user better configuration-ability. The problem lies within the fact that shopware doesn't detect these new parameters by itself. There is a shopware-method you can call which does this syncing, but before 5.3 there is no way to call it but by executing shopware itself. Having this functionality will prevent errors like _There's no such field here in the config_

See this PR for more Info:

https://github.com/shopware/shopware/pull/923/files

**Comment by emtii** [comment]
just created an PR for this.

**Comment by emtii** [comment]
This is done by @bestit-el-bardan dynamic shopware command runner.
